### ISSUE TITLE
each in scss 

### ISSUE THREAD

**Issue by rupertqin** [rupertqin/rupertqin.github.io#8]
```scss
$step-names: safeSys, watcher, circuit, machinery;
@each $name in $step-names {
    $i: index($step-names, $name);
    &.step-#{$name} { 
        .row-#{$name} {
            .cover {
                display: inline-block;
            }
        }
    }
}
```
